version: '3.9'

services:

  rabbit:
    image: "rabbitmq:management"
    hostname: rabbit
    container_name: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqldata
    environment:
      SA_PASSWORD: "Teste@1954"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1450:1433"
    networks:
      - backend

  jirafake:
    image: jirafake:latest
    container_name: jirafake
    ports:
      - 8081:80
    networks:
      - backend
    depends_on:
      - sqldata
      - rabbit

networks:
  backend:
    driver: bridge
