version: '3.9'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-container
    environment:
      SA_PASSWORD: "Teste@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - backend

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq-container
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  jirafaker:
    image: jirafaker:latest
    container_name: jirafake-container
    ports:
      - "8081:80"
    networks:
      - backend
    depends_on:
      - sql-server
      - rabbitmq

networks:
  backend:
    driver: bridge
