version: '3.8'

services:
  jirafake-api:
    image: jirafake-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sql-server
      - rabbitmq

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "SenhaSQL"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
